# Generated by Django 3.2.18 on 2023-12-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='encodings',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='similarity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
