# Generated by Django 3.2.18 on 2023-12-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231230_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='encodings',
            field=models.TextField(blank=True, default=None),
        ),
    ]
